config/routes.rb
CarmeBlanch::Application.routes.draw do
  root :to => "cuenta#index"
  resources :cuenta
  resources :var_confs
  resources :categoria
  resources :tipos
  resources :asientos 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  get "look_at_month" => "cuenta#look_at_month", :as => "look_at_month"

end

app/models/asiento.rb
class Asiento < ActiveRecord::Base
  validates :fecha, :tipo, :monto, :descripcion, :presence => true
  belongs_to :categorium
  belongs_to :tipo
  belongs_to :cuentum
  self.per_page = 10
  scope :cuentas, lambda {|cuentum_id| where "'asientos'.'cuentum_id' = ?", cuentum_id}
  scope :descen, order('fecha DESC, id DESC')
  scope :ascen, order('fecha ASC, id ASC')
  scope :sel_trozo,lambda {|fech1,fech2,categorium_id,cuentum_id,tipo_id| where("(date('asientos'.'fecha') >= ?) and 
                                              (date('asientos'.'fecha') <= ?) and 
                                              ('asientos'.'categorium_id' = ?) and
                                              ('asientos'.'cuentum_id' = ?) and
                                              ('asientos'.'tipo_id' = ?)",
                                               fech1,fech2,categorium_id,cuentum_id,tipo_id)}
  
  @mes_nom = {
              1 => "Enero",
              2 => "Febrero",
              3 => "Marzo",
              4 => "Abril",
              5 => "Mayo",
              6 => "Junio",
              7 => "Julio",
              8 => "Agosto",
              9 => "Septiembre",
              10 => "Octubre",
              11 => "Noviembre",
              12 => "Diciembre"
             }
                                              
  def self.informe_mensual
  end
  def self.informe_mes(mes,anno)
    gap = Date.new(anno,mes,1)
    gap2 = Date.today
    gap_ini = gap.at_beginning_of_month
    gap_end = gap.at_end_of_month  
    if (gap_ini.month==gap2.month) and (gap_ini.year==gap2.year) then
      gap_end=gap2
    end
    informe(gap_ini, gap_end)
  end
  def self.informe(gap_ini,gap_end)
    orden_cates=[4,12,13,1,3,5,11,7,2,14,10,15,16,17,18,19,20,8,6]
    salida = ["Informe del mes de #{@mes_nom[gap_ini.month]} hasta el dia #{gap_end.day}"]
    cates2 = Categorium.all.map{|x| [x.id,x.descripcion]}
    logger.debug "Cates_orig: #{cates2.inspect}"
    cates = []
    orden_cates.each do |h|
      cates.push(cates2[h-1]) if cates2[h-1]
    end
    logger.info "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --------> "
    logger.debug "hash: #{cates.inspect}"
    cuentas = Cuentum.all.map{|x| [x.id,x.nombre]}
    tipos = Tipo.all.map{|x| [x.id,x.descripcion]}
    n = 0
    cuentas=[[1,"Caja chica"]]
    cuentas.each do |cuenta|
          @suma_total = 0
      salida  << ["<h2>Cuenta #{cuenta[1]}</h2>"]
      tipos.each do |tipo|  
        suma = 0
        salida  << ["<h3>#{tipo[1]}</h3>"]
        cates.each do |cate|
          item = cate[1].capitalize
          logger.debug "item: #{item}"
          
          valor = self.sel_trozo(gap_ini,gap_end,cate[0],cuenta[0],tipo[0]).sum(:monto)
          if (valor != 0)
            suma += valor
            z = [item,valor]
            salida <<z
          end
        end
        item = "<b>Sub total #{tipo[1].downcase}</b>"
        z = [item,suma]
        if tipo[1]=='Ingreso'
          @suma_total += suma
        elsif tipo[1]=='Gasto'
          @suma_total -= suma
        end
        salida <<z
      end
      salida << ['<span class="green">Saldo mensual</span>',@suma_total]
    end
    salida
  end
  def save_pair(cuentum1_id,cuentum2_id,categorium1_id)
     if params[:asiento][:categorium_id]==categorium1_id then
      @params2=params[:asiento]
      params[:asiento][:cuentum_id]=@usercuenta
      if params[:asiento][:tipo_id]==2 then
        @params2[:tipo_id]=1
      else
        @params2[:tipo_id]=2
      end
      if params[:asiento][:cuentum_id]==cuentum2 then
        @params2[:cuentum_id]=cuentum1
      else
        @params2[:cuentum_id]=cuentum2
      end
      @asiento2 = Asiento.new(@params2)
      guardar = @asiento.save and @asiento2.save
    else
      guardar = @asiento.save
    end
  end

end

app/controllers/asientos_controller.rb
class AsientosController < ApplicationController
  # GET /asientos
  # GET /asientos.json
  load_and_authorize_resource
  
  def index    
    if params[:asiento]
      @usercuenta = params[:asiento][:cuentum_id] 
    elsif params[:cuentum_id]
      @usercuenta = params[:cuentum_id]
    else
      @usercuenta = 1
    end
    @asientos2 = Asiento.cuentas(@usercuenta).ascen
    @asientos = Asiento.cuentas(@usercuenta).descen.page(params[:page])
    logger.debug "METHOD: i n d e x  -------> #{params} @usercuenta = #{@usercuenta} "
    hoy=Date.today
    caja_cuenta=Cuentum.find(@usercuenta).nombre
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @asientos }
      format.csv { response.headers['Content-Disposition'] = "attachment; filename=\"asientos_#{hoy}_#{caja_cuenta}.csv\""}
    end
  end

  # GET /asientos/1
  # GET /asientos/1.json
  def show
    @asiento = Asiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @asiento }
    end
  end

  # GET /asientos/new
  # GET /asientos/new.json
  def new
    logger.debug "METHOD: n e w  -------> #{params} "
    if params[:asiento]
      @usercuenta = params[:asiento][:cuentum_id] 
    elsif params[:cuentum_id]
      @usercuenta = params[:cuentum_id]
    else
      @usercuenta = 1
    end

    @asiento = Asiento.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @asiento }
    end
  end

  # GET /asientos/1/edit
  def edit

    logger.debug "METHOD: e d i t  -------> #{params} "
    if params[:asiento]
      @usercuenta = params[:asiento][:cuentum_id] 
    elsif params[:cuentum_id]
      @usercuenta = params[:cuentum_id]
    else
      @usercuenta = 1
    end
    @asiento = Asiento.find(params[:id])
  end

  # POST /asientos
  # POST /asientos.json
  def create

    @asiento = Asiento.new(params[:asiento])
    if params[:asiento][:categorium_id]=="4" and 
      (  params[:asiento][:cuentum_id]=="2"  
      ) then
      guardar =save_pair("1","2",params)
    elsif params[:asiento][:categorium_id]=="9" and
      (  params[:asiento][:cuentum_id]=="1"  
      ) then
      guardar =save_pair("1","3",params)
    else
      guardar = @asiento.save
    end
    respond_to do |format|
      if guardar  
        format.html { redirect_to @asiento, :notice => 'El apunte fue creado.' }
        format.json { render :json => @asiento, :status => :created, :location => @asiento }
      else
        format.html { render :action => "new" }
        format.json { render :json => @asiento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /asientos/1
  # PUT /asientos/1.json
  def update
    @asiento = Asiento.find(params[:id])
    respond_to do |format|
      if @asiento.update_attributes(params[:asiento])
        format.html { redirect_to @asiento, :notice => 'El apunte fue cambiado.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @asiento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /asientos/1
  # DELETE /asientos/1.json
  def destroy
    @asiento = Asiento.find(params[:id])
    @usercuenta=@asiento.cuentum_id
    @asiento.destroy
  
    respond_to do |format|
      logger.debug "Asiento  D E S T R O Y E D -------> #{params} #{@usercuenta} "
      format.html { redirect_to asientos_url :cuentum_id => @usercuenta }
      format.json { head :ok }
    end
  end
def save_pair(cuentum1_id, cuentum2_id,params)
  @params2=params[:asiento]
  logger.debug "P A R A M S (0)-------> #{params[:asiento]} -> #{@usercuenta}"
  logger.debug "P A R A M S (00)-------> #{cuentum1_id} -> #{cuentum2_id}"
  if params[:asiento][:tipo_id]=="2" then
    @params2[:tipo_id]="1"
  else 
    @params2[:tipo_id]="2"
  end       
  if params[:asiento][:cuentum_id]==cuentum2_id then
    logger.debug "P A R A M S (1) -------> #{params[:asiento][:cuentum_id]} -> #{cuentum2_id} "
    @params2[:cuentum_id]=cuentum1_id
  else 
    logger.debug "P A R A M S (2) -------> #{params[:asiento][:cuentum_id]} -> #{cuentum2_id} "
    @params2[:cuentum_id]=cuentum2_id
  end       
  @asiento2 = Asiento.new(@params2)
  guardar = @asiento.save and @asiento2.save
end
end

app/helpers/asientos_helper.rb
module AsientosHelper
  def estado_caja(asientos)
    @caja = 0
    @lista_caja = Hash.new
    asientos.each do |asiento|
      if asiento.tipo_id == 1 then
        @caja += asiento.monto.to_d
      elsif asiento.tipo_id == 2 then
        @caja -= asiento.monto.to_d
      end
      caja = @caja
      @lista_caja[asiento.id] = caja
    end
      salida_caja = [@caja, @lista_caja]
  end
end

app/views/asientos/_form.html.erb
<%= form_for @asiento do |f| %>
  
  <% if @asiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asiento.errors.count, "error") %> prohibited this asiento from being saved:</h2>

      <ul>
        <% @asiento.errors.full_messages.each do |msg| %>
          <li><%= msg %><//li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :cuentum_id, :value => @usercuenta %>
  <b>Fecha:</b>
    <%= f.date_select(:fecha, :order => [:day,:month,:year]) %>
    <p><b><span><%= f.label :tipo %></span></b>
      <%= @tipos=Tipo.find(:all, :order=>"descripcion" )
         f.collection_select(:tipo_id, @tipos, :id, :descripcion, :include_blank => true) %> 
  <b>Categoría:</b>
	<%= @categoria=Categorium.find(:all,:order=>"descripcion")
	    f.collection_select(:categorium_id,@categoria,:id,:descripcion) %></p>
  		<p><b>Descripción:</b>
			<%= f.text_field :descripcion %></p>
		<p><b>Cantidad:</b>
			<%= f.text_field :monto %></p>
  <p><b>Observaciones:</b><br />
	<%= f.text_area :observaciones, :rows => 3 %></p>
  <p><%= f.submit "Guardar"%></p>
<% end %>
		<script>
		  $('#asiento_tipo_id').change(function(){			
		    if ($(this).children('option:selected').text() === 'Gasto') {
		      $('span').removeClass('ingreso').addClass('gasto');
		    } else if ($(this).children('option:selected').text() === 'Ingreso'){
		      $('span').removeClass('gasto').addClass('ingreso');
		    }  
		      else    {
		      $('span').removeClass('gasto').removeClass('ingreso');
		    }
		   });
		</script>

		
  

app/views/asientos/edit.html.erb
<h1>Modificando el apunte
<% cuentum = Cuentum.find(@usercuenta) %>
<%= cuentum.nombre%>  de <%= cuentum.moneda%></h1>
<%= render 'form' %>

<%= link_to "Cambiar de cuenta", cuenta_path %>
<%= form_tag asientos_path, :method => "get" do  %>
  <%= hidden_field_tag :cuentum_id, cuentum.id %>
  <%= button_tag 'Ver cuenta' %>
<% end %>
<%= link_to 'Mostrar', @asiento %> |

app/views/asientos/index.csv.erb
<% estado = estado_caja(@asientos2) %>
<%- headers = ["Id", "Fecha","Categoria","Tipo","Descripcion","Monto","Balance"] -%>
<%= CSV.generate_line headers, options = {:col_sep => ";", :row_sep => "\t", :quote_char => "'"} %>
<%- @asientos2.each do |n| -%>
<% if n.observaciones=='' then n.observaciones=" " end %>
<%- obs = n.observaciones.tr("^A-Za-z0-9 éóúíáÁÉÚÍÓñÑ/","") %>
<%- row = [ n.id, n.fecha,n.tipo.descripcion,n.categorium.descripcion,n.descripcion,obs,n.monto, estado[1][n.id]," "] -%>
<%= CSV.generate_line row, options = {:col_sep => ";", :row_sep => "\t", :quote_char => "'"}  %>
<%- end -%>

app/views/asientos/index.html.erb
<h1>Lista de apuntes contables</h1>

<h2>Cuenta <%= Cuentum.find(@usercuenta).nombre %></h2>
<% estado = estado_caja(@asientos2)%>

<h2> Estado de  <%= Cuentum.find(@usercuenta).nombre %>: 
  <% if estado[0] < 0 %>
    <span class="egreso">
      <%= estado[0].round(2) %>
    </span>
  <% elsif estado[0] > 0 %>
    <span class="ingreso">
      <%= estado[0].round(2) %>
    </span>
  <% else %>
  <% end %> 
  <%= Cuentum.find(@usercuenta).moneda %>
</h2>

<span class="nuevo_item">
  <% if can? :create, Asiento %>
    <%= form_tag new_asiento_path, :method => 'get' do %>
	  <%= hidden_field_tag :cuentum_id, @usercuenta %>
	  <%= button_tag 'Apunte nuevo' %>
    <% end %>
  <% end %>
</span>

<%= will_paginate_with_i18n @asientos %><br />

<table class="indice">

  <tr>
   <th>Fecha</th>
   <th>Tipo</th>
   <th>Categoria</th>
   <th>Descripcion</th>
   <th>Monto</th>
   <th>Evolución caja</th>
   <th></th>
   <th></th>
   <th></th>
  </tr>

  <% @asientos.each do |asiento| %>  
    <% if asiento.tipo_id == 2 then %>
      <tr class= "egreso <%= cycle('odd', 'even') -%>">
    <% elsif asiento.tipo_id == 1 %>
	  <tr class="ingreso <%= cycle('odd', 'even') -%>">
    <% else %>
	  <tr>
    <% end %>
  
      <td><%= asiento.fecha %></td>
      <td><%= asiento.tipo.descripcion %></td>
      <td><%= asiento.categorium.descripcion %></td>
      <td><%= asiento.descripcion %></td>
      <td class="num_align"> <%= asiento.monto.round(2) %></td>
      <% if estado[1][asiento.id] >0  %>
        <td class="ingreso">
      <% elsif estado[1][asiento.id] <0 %>
	    <td class="egreso">
      <% else %>
	    <td class="num_align">
      <% end %>
	  <%= estado[1][asiento.id].round(2) %>
	  </td>
      <td><%= link_to 'Mostrar', asiento %></td>
      <% if can? :update, asiento %>
        <td>
          <%= form_tag edit_asiento_path(asiento) , :method => "get" do  %>
			<%= hidden_field_tag :cuentum_id, asiento.cuentum_id %>
			<%= button_tag 'Modificar apunte' %>
		  <% end %>
		</td>
      <% end %>
      <%  if can? :destroy, asiento %>
        <td><%= link_to 'Eliminar', asiento, :confirm => '¿Está usted seguro?', :method => :delete %></td>
      <% end %>
    </tr> 
  <% end %>

</table>

<br />
<span class="nuevo_item">
  <% if can? :create, Asiento %>
    <%= form_tag new_asiento_path, :method => 'get' do %>
	  <%= hidden_field_tag :cuentum_id, @usercuenta %>
	  <%= button_tag 'Apunte nuevo' %>
    <% end %>	
  <% end %>
</span>
<%= link_to "Cambiar de cuenta", cuenta_path %>
<br />
<%= will_paginate_with_i18n @asientos %>
<br />
<%= link_to "Exportar a csv", request.parameters.merge({:format => :csv}) %>

app/views/asientos/new.html.erb
<div id="new">
  <h1>Apunte nuevo en la cuenta 
	<% cuentum = Cuentum.find(@usercuenta) %>
	<%= cuentum.nombre%> de <%= cuentum.moneda%></h1>

  <%= render 'form' %>

  <%= link_to "Cambiar de cuenta", cuenta_path %>
  <%= form_tag asientos_path, :method => "get" do  %>
    <%= hidden_field_tag :cuentum_id, cuentum.id %>
    <%= button_tag 'Ver cuenta' %>
  <% end %>
</div>

app/views/asientos/show.html.erb
<p>  
	Cuenta de <%= @asiento.cuentum.nombre %> en <%= @asiento.cuentum.moneda %><br />
    <% if @asiento.tipo.descripcion =='Gasto' %>
      <span id="gasto">
	<% else %>
	  <span id="ingreso">
	<% end %>
    <b>Tipo:</b>
      <%= @asiento.tipo.descripcion %>
   </span></p>
  <p>
    <b>Fecha:</b>
    <%= @asiento.fecha %>
  </p>

<p>
  <b>Categoría:</b>
  <%= @asiento.categorium.descripcion %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @asiento.descripcion %>
</p>

<p>
  <b>Monto:</b>
  <%= @asiento.monto %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @asiento.observaciones %>
</p>
<% if @asiento.observaciones =~ /\d/ then %>
  <% n_fot=sprintf("%04i",@asiento.observaciones.tr("^0-9","")) %>
  <% n_fot_long = sprintf("/home/zubi/guarderia-comedor/app/assets/images/image2/%s*",n_fot) %>
  <% fot1 = Dir.glob(n_fot_long)[0] %> 
  <% if fot1 then %>
  <% fot =fot1.split("/")[-1] %>
  <img src="/assets/image2/<%= fot %>" alt="factura" width="600" heigth="800">
  <% else %>
  Sin introducir el soporte documental
  <% end %>
<% else %>
  Sin soporte documental 
<% end %>
<div id="show">
<% if can? :update, Asiento %>
  <%= form_tag edit_asiento_path(@asiento) , :method => "get" do  %>
    <%= hidden_field_tag :cuentum_id, @asiento.cuentum_id %>
    <%= button_tag 'Modificar apunte' %>
  <% end %>
<% end %>

<%= form_tag asientos_path, :method => "get" do  %>
  <%= hidden_field_tag :cuentum_id, @asiento.cuentum_id %>
  <%= button_tag 'Ver cuenta' %>
<% end %>

<% if can? :create, Asiento %>
    <%= form_tag new_asiento_path, :method => 'get' do %>
	  <%= hidden_field_tag :cuentum_id, @asiento.cuentum_id %>
	  <%= button_tag 'Apunte nuevo' %>	
    <% end %>
<% end %>

<%= link_to "Cambiar de cuenta", cuenta_path %>

</div>