config/routes.rb
CarmeBlanch::Application.routes.draw do
  root :to => "cuenta#index"
  resources :cuenta
  resources :var_confs
  resources :categoria
  resources :tipos
  resources :asientos 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  get "look_at_month" => "cuenta#look_at_month", :as => "look_at_month"

end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  has_many :asientos
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  # GET /tipos
  # GET /tipos.json
    load_and_authorize_resource 
  def index
    @tipos = Tipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tipos }
    end
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tipo }
    end
  end

  # GET /tipos/new
  # GET /tipos/new.json
  def new
    @tipo = Tipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tipo }
    end
  end

  # GET /tipos/1/edit
  def edit
    @tipo = Tipo.find(params[:id])
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(params[:tipo])

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, :notice => 'Tipo was successfully created.' }
        format.json { render :json => @tipo, :status => :created, :location => @tipo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipos/1
  # PUT /tipos/1.json
  def update
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      if @tipo.update_attributes(params[:tipo])
        format.html { redirect_to @tipo, :notice => 'Tipo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo = Tipo.find(params[:id])
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to tipos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<h1>Listing tipos</h1>

<table>
  <tr>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipos.each do |tipo| %>
  <tr>
    <td><%= tipo.descripcion %></td>
    <td><%= link_to 'Show', tipo %></td>
    <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
    <td><%= link_to 'Destroy', tipo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New tipo</h1>

<%= render 'form' %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%= @tipo.descripcion %>
</p>


<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>