config/routes.rb
CarmeBlanch::Application.routes.draw do
  root :to => "cuenta#index"
  resources :cuenta
  resources :var_confs
  resources :categoria
  resources :tipos
  resources :asientos 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  get "look_at_month" => "cuenta#look_at_month", :as => "look_at_month"

end

app/controllers/cuenta_controller.rb
class CuentaController < ApplicationController
    load_and_authorize_resource
  # GET /cuenta
  # GET /cuenta.json
  def index
    @cuenta = Cuentum.all
    @usercuenta=0
    #@stats = Asiento.informe_hasta_dia
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cuenta }
    end
  end

  # GET /cuenta/1
  # GET /cuenta/1.json
  def show
    @cuentum = Cuentum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @cuentum }
    end
  end

  # GET /cuenta/new
  # GET /cuenta/new.json
  def new
    @cuentum = Cuentum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @cuentum }
    end
  end

  # GET /cuenta/1/edit
  def edit
    @cuentum = Cuentum.find(params[:id])
  end

  # POST /cuenta
  # POST /cuenta.json
  def create
    @cuentum = Cuentum.new(params[:cuentum])

    respond_to do |format|
      if @cuentum.save
        format.html { redirect_to @cuentum, :notice => 'Cuentum was successfully created.' }
        format.json { render :json => @cuentum, :status => :created, :location => @cuentum }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cuentum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cuenta/1
  # PUT /cuenta/1.json
  def update
    @cuentum = Cuentum.find(params[:id])

    respond_to do |format|
      if @cuentum.update_attributes(params[:cuentum])
        format.html { redirect_to @cuentum, :notice => 'Cuentum was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cuentum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cuenta/1
  # DELETE /cuenta/1.json
  def destroy
    @cuentum = Cuentum.find(params[:id])
    @cuentum.destroy

    respond_to do |format|
      format.html { redirect_to cuenta_url }
      format.json { head :ok }
    end
  end
  def look_at_month
    logger.debug "METHOD: look_at_month  -------> #{params}"
    mes = params[:date][:month].to_i
    anno = params[:date][:year].to_i
    @stats = Asiento.informe_mes(mes,anno)
    respond_to do |format|
      format.html # look_at_month.html.erb
      format.json { render :json => @cuenta }
    end
  end
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/views/cuenta/_form.html.erb
<%= form_for(@cuentum) do |f| %>
  <% if @cuentum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cuentum.errors.count, "error") %> No se permite guardar:</h2>

      <ul>
      <% @cuentum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
<div class="field">
    <%= f.label :moneda %><br />
    <%= f.text_field :moneda %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cuenta/edit.html.erb
<h1>Editing cuentum</h1>

<%= render 'form' %>

<%= link_to 'Show', @cuentum %> |
<%= link_to 'Back', cuenta_path %>

app/views/cuenta/index.html.erb
<% if can? :create, Asiento %>
  <div id="ver_apuntes">

  <p>Ver apuntes de las cuentas</p>
  <%= form_tag asientos_path, :method => "get" do  %>
    <%= radio_button_tag(:cuentum_id, "1",:checked => true) %>
    <%= label_tag(:cuentum_id_1, "Caja chica") %><br />
    <%= radio_button_tag(:cuentum_id, "2") %>
    <%= label_tag(:cuentum_id_2, "Banco") %><br /> 
	<!-- 
    <%= radio_button_tag(:cuentum_id, "3") %>
    <%= label_tag(:cuentum_id_3, "Efectivo") %><br /> 
		-->
    <%= button_tag 'Ver cuenta' %>
  <% end %>
  </div>
<% end %>

<div id="ver_mes">
    <p>Ver resumen mensual</p>
    <%= form_tag look_at_month_path, :controller => "cuenta",:method => "get" do  %>
    <%= select_month(Date.today) %>
    <%= select_year(Date.today) %>
    <%= button_tag 'Ver ' %>
  <% end %>
</div>

<% if can? :create, Asiento %>
  <div id="new_apunte">
    <p>Añadir apuntes a las cuentas</p>
    <%= form_tag new_asiento_path, :method => "get" do  %>
      <%= radio_button_tag(:cuentum_id, "1",:checked => true) %>
      <%= label_tag(:cuentum_id_1, "Caja chica") %><br />
      <%= radio_button_tag(:cuentum_id, "2") %>
      <%= label_tag(:cuentum_id_2, "Banco") %><br />
	    <!-- 
      <%= radio_button_tag(:cuentum_id, "3") %>
      <%= label_tag(:cuentum_id_3, "Efectivo") %><br /> 
			-->
      <p><%= button_tag 'Añadir apunte' %></p>
   <% end %>
  </div>
<% end %>

app/views/cuenta/look_at_month.html.erb
<div >
  <h2>
    <thead>
      <%= @stats[0]%>
    </thead>
  </h2>
  <table id="show">
    <tr>
      <td>
      <% notini = false %>
      <% @stats[1..-1].each do |z| %>
        <% if z[0].to_s.index('<h2>') then %>
          <%  if notini then %>
            </table></td><td>
            <table><tr>
          <% else %>
            <% notini=true %>
            <table><tr>
          <% end %>
        <% else %>
          <tr>
        <% end %>
        <% z.each do |w| %>
          <td><%=raw w %></td>
        <% end %>
        </tr>
      <% end %>
    </table>
    </td>
    </tr> 
  </table>
</div>

app/views/cuenta/new.html.erb
<h1>New cuentum</h1>

<%= render 'form' %>

<%= link_to 'Back', cuenta_path %>

app/views/cuenta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @cuentum.nombre %>
</p>
<p>
  <b>Moneda:</b>
  <%= @cuentum.moneda %>
</p>


<%= link_to 'Edit', edit_cuentum_path(@cuentum) %> |
<%= link_to 'Back', cuenta_path %>