config/routes.rb
CarmeBlanch::Application.routes.draw do
  root :to => "cuenta#index"
  resources :cuenta
  resources :var_confs
  resources :categoria
  resources :tipos
  resources :asientos 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  get "look_at_month" => "cuenta#look_at_month", :as => "look_at_month"

end

app/models/var_conf.rb
class VarConf < ActiveRecord::Base
end

app/controllers/var_confs_controller.rb
class VarConfsController < ApplicationController
  # GET /var_confs
  # GET /var_confs.json
    load_and_authorize_resource
  def index
    @var_confs = VarConf.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @var_confs }
    end
  end

  # GET /var_confs/1
  # GET /var_confs/1.json
  def show
    @var_conf = VarConf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @var_conf }
    end
  end

  # GET /var_confs/new
  # GET /var_confs/new.json
  def new
    @var_conf = VarConf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @var_conf }
    end
  end

  # GET /var_confs/1/edit
  def edit
    @var_conf = VarConf.find(params[:id])
  end

  # POST /var_confs
  # POST /var_confs.json
  def create
    @var_conf = VarConf.new(params[:var_conf])

    respond_to do |format|
      if @var_conf.save
        format.html { redirect_to @var_conf, :notice => 'Var conf was successfully created.' }
        format.json { render :json => @var_conf, :status => :created, :location => @var_conf }
      else
        format.html { render :action => "new" }
        format.json { render :json => @var_conf.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /var_confs/1
  # PUT /var_confs/1.json
  def update
    @var_conf = VarConf.find(params[:id])

    respond_to do |format|
      if @var_conf.update_attributes(params[:var_conf])
        format.html { redirect_to @var_conf, :notice => 'Var conf was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @var_conf.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /var_confs/1
  # DELETE /var_confs/1.json
  def destroy
    @var_conf = VarConf.find(params[:id])
    @var_conf.destroy

    respond_to do |format|
      format.html { redirect_to var_confs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/var_confs_helper.rb
module VarConfsHelper
end

app/views/var_confs/_form.html.erb
<%= form_for(@var_conf) do |f| %>
  <% if @var_conf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@var_conf.errors.count, "error") %> prohibited this var_conf from being saved:</h2>

      <ul>
      <% @var_conf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :name_foto %><br />
    <%= f.text_field :name_foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/var_confs/edit.html.erb
<h1>Editing var_conf</h1>

<%= render 'form' %>

<%= link_to 'Show', @var_conf %> |
<%= link_to 'Back', var_confs_path %>

app/views/var_confs/index.html.erb
<h1>Listing var_confs</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Name foto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @var_confs.each do |var_conf| %>
  <tr>
    <td><%= var_conf.titulo %></td>
    <td><%= var_conf.name_foto %></td>
    <td><%= link_to 'Show', var_conf %></td>
    <td><%= link_to 'Edit', edit_var_conf_path(var_conf) %></td>
    <td><%= link_to 'Destroy', var_conf, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Var conf', new_var_conf_path %>

app/views/var_confs/new.html.erb
<h1>New var_conf</h1>

<%= render 'form' %>

<%= link_to 'Back', var_confs_path %>

app/views/var_confs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @var_conf.titulo %>
</p>

<p>
  <b>Name foto:</b>
  <%= @var_conf.name_foto %>
</p>


<%= link_to 'Edit', edit_var_conf_path(@var_conf) %> |
<%= link_to 'Back', var_confs_path %>